version: "3.5"

x-common-app-settings: &common_app_settings
  image: hotwire-test:local-dev
  build:
    context: .
    dockerfile: ./Dockerfile-dev
  tty: true
  environment:
    DATABASE_HOST: postgres
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postpass
    REDIS_HOST: redis
    RAILS_ENV: development
    WEBPACKER_DEV_SERVER_HOST: webpack-dev-server
  volumes:
    - .:/app:delegated
    - type: tmpfs
      target: /app/tmp/pids/
  networks:
    - default
services:
  app:
    <<: *common_app_settings
    command: bin/start
    ports:
      - "3000:3000"
    depends_on:
      - webpack-dev-server
      - postgres
      - redis
  webpack-dev-server:
    <<: *common_app_settings
    environment:
      NODE_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: bin/webpack-dev-server
    ports:
      - "3035:3035"
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postpass
    ports:
      - "5432:5432"
    volumes:
      - hotwire-rails-postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
    volumes:
      - hotwire-rails-redis:/var/lib/redis/data
volumes:
  hotwire-rails-postgres:
  hotwire-rails-redis:
