version: "3.5"

x-common-app-settings: &common_app_settings
  image: hotwire-test:local-dev
  build:
    context: .
    dockerfile: ./Dockerfile-dev
  tty: true
  environment:
    DATABASE_HOST: postgres
    REDIS_HOST: redis
    RAILS_ENV: development
  volumes:
    - .:/app:delegated
    - type: tmpfs
      target: /app/tmp/pids/
  networks:
    - default
    - postgres
    - redis

services:
  app:
    <<: *common_app_settings
    command: bin/start
    ports:
      - "3000:3000"
  webpack-dev-server:
    <<: *common_app_settings
    command: bin/webpack-dev-server
    ports:
      - "3035:3035"

networks:
  postgres:
    external: true
  redis:
    external: true
